### ISSUE TITLE
Compile issue on gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)

### ISSUE THREAD

**Issue by nylander** [simonwhelan/prequal#1]
Hi Simon!

On a Ubuntu Linux 17.04, gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2), I had to include cmath:

To deal with undeclared functions `pow`, and `square`, add `#include <cmath>` in files `ZorroInterface.cpp`, and `prequal.cpp`.
Thanks
Johan

**Comment by simonwhelan** [comment]
Hi Johan,

Thanks for reporting the bug and sorry for the delay - I've added cmath to the main file header and added a bunch of other fixes that should make it more stable across platforms. 

/Simon
